---

- name: Build the hello-world project
  command: >
    chdir=/tmp/kotlin-hello-world mvn clean package spring-boot:repackage
  tags: hello-world

- name: Copy
  copy:
    src: ../files/etc/init.d/hello-world.sh
    dest: /etc/init.d/hello-world.sh
    mode: 0755
  tags: java

- name: Run the hello-world
  shell: cd /tmp; nohup /etc/init.d/hello-world.sh </dev/null >/dev/null 2>&1 &